[project]
org-name= "ballerinax"
version= "1.3.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["ballerina", "salesforce", "sfdc", "client", "connector"]
repository = "https://github.com/ballerina-platform/module-salesforce"

[platform]
target = "java8"

  [[platform.libraries]]
  module = "sfdc"
  path = "../emp-wrapper/target/emp-wrapper-1.3.0.jar"
