name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - run: mvn clean package -pl emp-wrapper
          - name: Ballerina Build
            uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
            with:
              args:
                build -a -c --skip-tests --sourceroot sfdc-connector
